### ISSUE TITLE
Changed Home Page To Solar System Page

### ISSUE THREAD

**Issue by juancwu** [terrifricker/our-solar-system#59]
I want to change the home page to be the solar system page. This is because we do not really have other content except for the planet's information so I do not see the use of an extra step to get to planet page.

Suggestion: Use solar system page as our homepage.

**Comment by terrifricker** [comment]
Exactly!  Please do.

**Comment by terrifricker** [comment]
Oh, I misunderstood.  Since you assigned me, the workflow would be that I change it.  (Besides the fact that it is something I can actually do.)  Thanks

**Comment by terrifricker** [comment]
Actually, I can't because I don't know react well enough to confidently make the change.  I can see the old Home.js file and figure it would be deleted, then changes would be made in app.js to not import it and not give it a path, but I don't think those are the only changes needed?  Some other file must add it to "root"?

It's time I read your react files to help me learn.

**Comment by terrifricker** [comment]
I can read through the commits on your pull request.
